### PR TITLE
Update mix.exs to Phoenix 1.4 

### PR DESCRIPTION
**Pull request by nelsonic**
@iteles just noticed that I forgot to update the version of Phoenix in the mix.exs file ... 🙄 (_derp!_)
+ [x] update version of Phoenix to v.1.4 for https://github.com/dwyl/learn-phoenix-framework/issues/118
+ [x] update config to use `Phoenix.json_library()` https://github.com/dwyl/phoenix-chat-example/pull/13#issuecomment-439274300

> note: I have it updated on my "personal walkthrough" of this example: https://github.com/nelsonic/phoenix-chat-v1.4/blob/059db8850bee14d95f0caeb12d54d7485d402503/mix.exs#L36 but forgot to do it here!

Thanks for reviewing/merging. 👍

### CODE REVIEW

**Comment by nelsonic** [comment]
https://travis-ci.org/dwyl/phoenix-chat-example/builds/455809393#L667
image

```
** (ArgumentError) invalid :json_decoder option. The module Poison is not loaded and could not be found
```
😞

**Comment by nelsonic** [comment]
https://github.com/dwyl/phoenix-chat-example/blob/8047714b07cb98e8daf98e21b838fffa0e7df8fa/lib/chat_web/endpoint.ex#L33

should be:
```elixir
json_decoder: Phoenix.json_library()
```
https://github.com/nelsonic/phoenix-chat-v1.4/blob/059db8850bee14d95f0caeb12d54d7485d402503/lib/chat_web/endpoint.ex#L32

**Comment by nelsonic** [comment]
```sh
warning: failed to load Jason for Phoenix JSON encoding
(module Jason is not available).

Ensure Jason exists in your deps in mix.exs,
and you have configured Phoenix to use it for JSON encoding by
verifying the following exists in your config/config.exs:

    config :phoenix, :json_library, Jason


  (phoenix) lib/phoenix.ex:40: Phoenix.start/2
  (kernel) application_master.erl:277: :application_master.start_it_old/4
```

**Comment by nelsonic** [comment]
image

run:
```
cd assets && npm install && cd ..
```

**Comment by nelsonic** [comment]
```
Generated chat app
** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "messages" already exists
    (ecto_sql) lib/ecto/adapters/sql.ex:590: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql) lib/ecto/adapters/sql.ex:677: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql) lib/ecto/migration/runner.ex:272: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql) lib/ecto/migration/runner.ex:105: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/ecto/migration/runner.ex:103: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
```

Tried to "drop" using mix task: https://hexdocs.pm/ecto/Mix.Tasks.Ecto.Drop.html
```
mix ecto.drop
mix ecto.create
mix ecto.migrate
mix test
```
Failed!

had to go nuclear: https://stackoverflow.com/questions/7073773/drop-postgresql-database-through-command-line
```
psql -U postgres -c "drop database chat_test"
```

_obviously_ I got the following error:
```
-bash: psql: command not found
```
(_new computer ..._)

see: https://postgresapp.com/documentation/cli-tools.html
```
sudo mkdir -p /etc/paths.d &&
echo /Applications/Postgres.app/Contents/Versions/latest/bin | sudo tee /etc/paths.d/postgresapp
```
Once `psql` was linked, I was able to drop the `chat_dev` database and re-run the tests:

image

**Comment by pdxrod** [comment]
I have the same problem as above
" The module Poison is not loaded and could not be found" when I run 'mix phx.server'
I've followed all the steps above, and it makes no difference
in mix.exs
  {:phoenix, "~> 1.4.0"},
  {:json, "~> 1.2"}
in endpoint.ex
    json_decoder: Phoenix.json_library()
In config.exs
  config :phoenix, json_library: Jason
None of these steps solve the problem
They just make the error message different:
"The module Jason is not loaded and could not be found" when I run 'mix phx.server'

**Pull request merged**
