### PR TITLE
PR:`auth` 🔐  + `Tailwind` ✨ 

### LINKED ISSUE #54: Feat: Add `auth_plug` to Phoenix Chat Example so people can authenticate 🔐
This tutorial is currently _already_ quite [popular](https://github.com/dwyl/phoenix-chat-example/stargazers). 🤩 🎉 
We can take it to the **_next_ level** by adding **`auth`** via [**`auth_plug`**](https://github.com/dwyl/auth_plug) using **`ONE Environment Variable™`**! 🚀 

# Story

As a **`person`** learning **`Elixir/Phoenix`** 🌱 
**I need** a **_fully_ featured example** including **`auth`** 🔐 
**So _that_** I can **learn** the [**`Tech Stack`**](https://github.com/dwyl/technology-stack) as _fast_ as possible and contribute in the team. 🙌 

@LuchoTurtle hopefully you can identify with this story. 🤞 

# Todo

+ [x] Create a new markdown file called `auth.md` and link to it from the main `README.md`
+ [x] Document each step in the setup process for adding authentication to this Chat App.
+ [x] Add [**`auth_plug`**](https://github.com/dwyl/auth_plug) to this project, see: https://github.com/dwyl/auth_plug_example#how
  + [ ] Along the way, if you get stuck, _please_ open issues! 🙏
> Our objective is to make all our docs "standalone"; i.e. anyone can pick up and understand _exactly_ what is going on without hitting any hurdles. We _acknowledge_ that we aren't there [_yet_](https://xkcd.com/1513/): https://github.com/dwyl/auth/issues/153#issuecomment-945662561 so we need _lots_ of help to get to the point where `auth` has _superb_ documentation. 
+ [x] Figure out if `conn.assigns.person` is available in a Channel (JS) request for channels.
+ [x] Add Tailwind for Layout/Styling see: [github.com/dwyl/learn-tailwind#part-2-tailwind-in-phoenix](https://github.com/dwyl/learn-tailwind#part-2-tailwind-in-phoenix)

Very happy to [_pair_](https://en.wikipedia.org/wiki/Pair_programming) on this if you want an idea of my workflow.

Hopefully this is a fun challenge that will help you to learn a bit of the [**`Tech Stack`**](https://github.com/dwyl/technology-stack) 🤞 
and make it a _lot_ easier for the [_next_](https://blog.codinghorror.com/coding-for-violent-psychopaths/) people joining the team. 😉 

image

### LINKED ISSUE #121: Add `Tailwind CSS` ✨
It's occurred to me that the CSS/Styles in this example are "meh" ...

image

And with the addition of **`Tailwind CSS`** in **`Phoenix 1.7`** https://github.com/dwyl/learn-phoenix-framework/issues/152
We can _significantly_ improve the UI! 

Luckily, we've already done the "hard" part in: [dwyl/phoenix-liveview-chat-example#15-**tailwind-css-stylin**](https://github.com/dwyl/phoenix-liveview-chat-example/tree/eabe4be121061b213a70159248c4869cdb8335ac#15-tailwind-css-stylin)

liveview-chat-with-tailwind

So I _expect_ that we can _borrow_ much of the code from that tutorial 
and _estimate_ that it shouldn't take us more than **`T1h`** to get it done. 
(_probably much less Time/Effort, but being conservative for any layout issues ..._)

# Todo

+ [x] Add docs section to Main `README.md` for adding `Tailwind`
+ [x] Add `Tailwind CSS` to this `Phoenix 1.6.x` project _manually_
+ [x] Attempt to borrow the code from: https://github.com/dwyl/phoenix-liveview-chat-example/blob/main/lib/liveview_chat_web/templates/layout/root.html.heex
+ [x] Adapt as needed

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #121 

+ [x] #54 by adding [**`auth_plug`**](https://github.com/dwyl/auth_plug)
+ [x] https://github.com/dwyl/phoenix-chat-example/issues/121
+ [x] https://github.com/dwyl/phoenix-chat-example/issues/122

This is meant to expand the tutorial by adding generic authentication through different providers.

~~This is very much a work-in-progress that is currently blocked because of ["the `auth_plug` package is not properly working on recent version of Elixir" issue](https://github.com/dwyl/auth_plug/issues/76#issuecomment-1277950888)~~ 

Just pushing it for future reference 😄

### CODE REVIEW

**Comment by nelsonic** [comment]
Depends on: https://github.com/dwyl/auth/issues/246

Continue: https://github.com/dwyl/phoenix-chat-example/blob/add-auth/auth.md

**Comment by nelsonic** [comment]
Ok, I've got `auth_plug` working on my localhost: ✅ 

image

Don't have more time to spend on tidying the UI/layout so assigning back to you @LuchoTurtle 👌

**Comment by nelsonic** [comment]
Tests should be at **`100%`** https://github.com/dwyl/phoenix-chat-example/actions/runs/3490512730/jobs/5842037774#step:7:199

Please confirm when you can. 👌

**Comment by LuchoTurtle** [comment]
Gonna have a look at this after the https://github.com/dwyl/product-roadmap/issues/40 Flutter preliminary repos and [`Edit Timers`](https://github.com/dwyl/mvp/tree/edit-timer) are properly merged 👍

**Comment by nelsonic** [comment]
Yeah, totes agree **`Flutter`** is **`P1`** this is **`P2`**. 👍 
iDon't expect this PR will need more than an hour of your time. 🤞 
It will be a _superb_ showcase for our **`auth`**/**`auth_plug`**. 🚀

**Comment by LuchoTurtle** [comment]
@nelsonic I've pushed some updates for styling and improving overall experience.

However, I can't seem to get the auth working the same way you have. I can sign in just fine through Github but the `givenName` property inside the `person` socket assign seems to be `nil` in my case (in your `.gif` it seems to work fine - it says "Nelson").

I've checked out the commit before I made any chances and it's not working on my computer, even after deleting the `build` folder and rebuilding the project 😞 

Screenshot 2022-11-21 at 21 20 23

**Comment by nelsonic** [comment]
@LuchoTurtle great UI updates! 🎉 
If you have time, stay on the Zoom call and we can worth through this today. 👌

**Comment by nelsonic** [comment]
Maybe we should fallback to using `person.username` if the `person.givenName` is not set? 💭

**Comment by LuchoTurtle** [comment]
Apparently, the "username" field is not being passed on in my profile. This is out of the scope of this PR so it shouldn't be a problem. 
The fallback here was using as a "guest" and I'm going to keep it that way 👍

**Comment by nelsonic** [comment]
@LuchoTurtle not fixing the display of the name and not opening an issue to record it is no bueno ... 🙅 
image

If our `Auth` code is not returning your GitHub username that's something we _absolutely_ want to fix as a ***`P1`***.

**Comment by nelsonic** [comment]
To be clear: I'm _really_ glad that you've uncovered this issue. 🎉 
I just want there to be an issue so we can _fix_ it. 
Not say that it's "beyond the scope" to fix it. 
It will be a problem in our App if someone logs-in and doesn't have a name and doesn't know _why_... 🤷‍♂️

**Comment by LuchoTurtle** [comment]
@nelsonic want to meet up on Zoom? You showed the `username` field this morning on the standup but I can't seem to find it on https://github.com/dwyl/auth_plug. Perhaps you showed local changes?

I'm debugging `auth_plug` and there are no mentions of `username`, besides `givenName` :/

image

**Comment by nelsonic** [comment]
Issue created: https://github.com/dwyl/auth/issues/248 🔥 
Debugging it now. 🤞

**Comment by LuchoTurtle** [comment]
I was going to do something similar to this but you beat me to it https://github.com/dwyl/phoenix-chat-example/pull/120/commits/fab97d343db3c31143b6764fdbf7de92883f71f6

However, is this working for you? Because on my `localhost` it errors out, it *still* can't find the username.

image

**Comment by nelsonic** [comment]
Build failing because `dbg/1` not found. 
https://github.com/dwyl/phoenix-chat-example/actions/runs/3532464774/jobs/5926843074#step:7:184
image

Need to update the version of `Elixir` as per: https://github.com/dwyl/auth/issues/248#issuecomment-1324807156

**Comment by nelsonic** [comment]
Build failing because `dbg/1` not found. 
https://github.com/dwyl/phoenix-chat-example/actions/runs/3532464774/jobs/5926843074#step:7:184
image

Need to update the version of `Elixir` as per: https://github.com/dwyl/auth/issues/248#issuecomment-1324807156

**Comment by nelsonic** [comment]
Build failing because `dbg/1` not found. 
https://github.com/dwyl/phoenix-chat-example/actions/runs/3532464774/jobs/5926843074#step:7:184
image

Need to update the version of `Elixir` as per: https://github.com/dwyl/auth/issues/248#issuecomment-1324807156

**Comment by LuchoTurtle** [comment]
@nelsonic 
I can do that. 

I had to reset the API key to get it working.

Screenshot 2022-11-23 at 13 36 35


It works now. Thanks

**Comment by LuchoTurtle** [comment]
Nvm then. 
In that case, since the issue was resolved, I will submit this to review.

**Comment by LuchoTurtle** [comment]
Well, with this fixed, the PR should be admissable for review.

If you have any feedback on the UI, please comment here @nelsonic  👍

**Comment by nelsonic** [comment]
Gonna take a final look at this when I get back to my desk. ⏳ (thanks!)

**Comment by nelsonic** [comment]
Sorry this has taken me a ***`while`*** to get back to ... ⏳ 
Looking at it _now_! 🧑‍💻

**Comment by nelsonic** [comment]
Before Tailwind:
image

With _compact_/_minimalist_ Tailwind UI:
image

Sadly, some genius decided to write swear words in our App. It's what we get for not enforcing auth. 🙄 
Anyway,

**Pull request merged**
